apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: example
resources:
- deployment.yaml
- serviceaccount.yaml

configMapGenerator:
  - name: srcs
    files:
      - hello.c
