apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: watchsa

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - rbac

configMapGenerator:
  - name: watchsa
    files:
      - watchsa.sh
